#!/usr/bin/env bash
# =============================================================================
# install_wannier90.sh — build Wannier90 into toolchain/install/wannier90-<ver>
#
# UCRT64 gfortran (+ MS-MPI via mpifort). Produces libwannier and Fortran
# modules (w90_wannierise.mod) for vasp_cmake FindWANNIER90.cmake.
#
# Download / extract policy (mandatory):
#   retrieve_package → SHA256 vs package_versions.sh pin (cached re-verified)
#   extract_verified_archive → verify_before_extract again, then tar
#   Never unpack on mismatch (bad file deleted, non-zero exit).
#
# Usage (MSYS2 UCRT64):
#   bash toolchain/scripts/install_wannier90.sh
# =============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TOOLCHAIN_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
# shellcheck source=../package_versions.sh
source "${TOOLCHAIN_ROOT}/package_versions.sh"
# shellcheck source=../lib/tool_kit.sh
source "${TOOLCHAIN_ROOT}/lib/tool_kit.sh"

SCRIPT_NAME="install_wannier90.sh"
load_package_vars wannier90

BUILDDIR="${TOOLCHAIN_BUILDDIR:-${TOOLCHAIN_ROOT}/build}"
INSTALL_ROOT="${TOOLCHAIN_INSTALL_ROOT:-${TOOLCHAIN_ROOT}/install}"
PKG_BUILD="${BUILDDIR}/wannier90-${wannier90_ver}"
PKG_PREFIX="${INSTALL_ROOT}/wannier90-${wannier90_ver}"
TARBALL="${BUILDDIR}/wannier90-${wannier90_ver}.tar.gz"
SRC_DIR="${PKG_BUILD}/wannier90-${wannier90_ver}"

log() { printf '\033[1;34m[wannier90]\033[0m %s\n' "$*"; }
die() { printf '\033[1;31m[wannier90]\033[0m %s\n' "$*" >&2; exit 1; }

if [ "${MSYSTEM:-}" != "UCRT64" ]; then
  if [ "${ALLOW_NON_UCRT64:-}" = "1" ]; then
    report_warning "MSYSTEM=${MSYSTEM:-unset} (expected UCRT64); continuing due to ALLOW_NON_UCRT64=1"
  else
    die "MSYSTEM=${MSYSTEM:-unset}; must run in MSYS2 UCRT64 (or set ALLOW_NON_UCRT64=1)"
  fi
fi

command -v gfortran >/dev/null 2>&1 || die "gfortran not found on PATH"
command -v make >/dev/null 2>&1 || die "make not found on PATH"
MPIF90_BIN="${MPIF90:-}"
if [ -z "${MPIF90_BIN}" ]; then
  if command -v mpifort >/dev/null 2>&1; then
    MPIF90_BIN=mpifort
  elif command -v mpif90 >/dev/null 2>&1; then
    MPIF90_BIN=mpif90
  else
    die "mpifort/mpif90 not found (need mingw-w64-ucrt-x86_64-msmpi)"
  fi
fi

mkdir -p "${BUILDDIR}" "${INSTALL_ROOT}"

# Idempotent: skip rebuild if library + required module already installed
if [ -f "${PKG_PREFIX}/lib/libwannier.a" ] && [ -f "${PKG_PREFIX}/include/w90_wannierise.mod" ]; then
  if [ "${FORCE_REBUILD:-0}" != "1" ]; then
    log "already installed at ${PKG_PREFIX} (set FORCE_REBUILD=1 to rebuild)"
    exit 0
  fi
  log "FORCE_REBUILD=1: removing ${PKG_PREFIX}"
  rm -rf "${PKG_PREFIX}"
fi

log "version=${wannier90_ver}"
log "pin_sha256=${wannier90_sha256}"
log "prefix=${PKG_PREFIX}"
log "jobs=$(toolchain_jobs) F90=gfortran MPIF90=${MPIF90_BIN}"

# Cache reuse only after SHA256 matches pin; mismatch deletes + re-downloads
retrieve_package "${wannier90_sha256}" "${TARBALL}" "${wannier90_url}" ||
  die "retrieve_package failed (SHA256 pin ${wannier90_sha256})"

rm -rf "${PKG_BUILD}"
mkdir -p "${PKG_BUILD}"
# Re-verify pin immediately before unpack — never blind extract
extract_verified_archive "${wannier90_sha256}" "${TARBALL}" -C "${PKG_BUILD}" ||
  die "extract_verified_archive refused unpack (SHA256 gate)"
[ -d "${SRC_DIR}" ] || die "extract failed: expected ${SRC_DIR}"

# Serial COMMS for embedding into VASP: a COMMS=mpi libwannier.a pulls
# mpi_scatterv_/mpi_gatherv_ that MS-MPI gfortran stubs do not satisfy at
# VASP link time (static archive order / missing Fortran bindings).
# VASP already owns MPI; FindWANNIER90 only needs libwannier + modules.
cat > "${SRC_DIR}/make.inc" << EOF
# Generated by install_wannier90.sh (MSYS2 UCRT64, serial for VASP link)
F90 = gfortran
MPIF90 = ${MPIF90_BIN}
FCOPTS = -O3 -fallow-argument-mismatch
LDOPTS = -O3
LIBS = -lopenblas
COMMS = serial
EOF

log "building libwannier (make lib)"
(
  cd "${SRC_DIR}"
  make clean >/dev/null 2>&1 || true
  make lib -j"$(toolchain_jobs)"
)

LIB_A="${SRC_DIR}/libwannier.a"
[ -f "${LIB_A}" ] || die "build failed: missing ${LIB_A}"

MOD_SRC=""
if [ -f "${SRC_DIR}/src/w90_wannierise.mod" ]; then
  MOD_SRC="${SRC_DIR}/src"
elif [ -f "${SRC_DIR}/w90_wannierise.mod" ]; then
  MOD_SRC="${SRC_DIR}"
else
  _mod="$(find "${SRC_DIR}" -name 'w90_wannierise.mod' -print -quit || true)"
  [ -n "${_mod}" ] && MOD_SRC="$(dirname "${_mod}")"
fi
[ -n "${MOD_SRC}" ] && [ -f "${MOD_SRC}/w90_wannierise.mod" ] ||
  die "build failed: w90_wannierise.mod not found under ${SRC_DIR}"

mkdir -p "${PKG_PREFIX}/lib" "${PKG_PREFIX}/include"
cp -f "${LIB_A}" "${PKG_PREFIX}/lib/libwannier.a"
cp -f "${MOD_SRC}"/*.mod "${PKG_PREFIX}/include/"

SETUP_FILE="${PKG_PREFIX}/setup_wannier90"
cat > "${SETUP_FILE}" << EOF
# Wannier90 ${wannier90_ver} — source this file (bash)
# FindWANNIER90: library NAMES wannier; module w90_wannierise.mod
_w90_root="\$(cd "\$(dirname "\${BASH_SOURCE[0]}")" && pwd)"
export WANNIER90_ROOT="\${_w90_root}"
case ":\${CMAKE_PREFIX_PATH}:" in
  *:"\${_w90_root}":*) ;;
  *) export CMAKE_PREFIX_PATH="\${_w90_root}\${CMAKE_PREFIX_PATH:+:\${CMAKE_PREFIX_PATH}}" ;;
esac
unset _w90_root
EOF

log "installed:"
log "  ${PKG_PREFIX}/lib/libwannier.a"
log "  ${PKG_PREFIX}/include/w90_wannierise.mod"
log "  ${SETUP_FILE}"
report_timing "install_wannier90"