#!/usr/bin/env bash
# =============================================================================
# install_vtst.sh — fetch vtstcode into toolchain/install/vtst-<ver>/
#
# Source-only (no compile). Pins henkelmangroup/vtstcode via package_versions.sh
# (commit + SHA256 of the GitHub archive). Installs the vtstcode6.6.0 tree and
# writes setup_vtst exporting VTST_CODE_DIR (does not override a pre-set value).
#
# Usage (MSYS2 UCRT64, from repo root):
#   bash toolchain/scripts/install_vtst.sh
#   # or: OPTIONAL_LIBS="... vtst" bash toolchain/scripts/install_optional.sh
#
# Then: export VASP_VTST=ON && bash toolchain/build_vasp.sh
# =============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TOOLCHAIN_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
# shellcheck source=../package_versions.sh
source "${TOOLCHAIN_ROOT}/package_versions.sh"
# shellcheck source=../lib/tool_kit.sh
source "${TOOLCHAIN_ROOT}/lib/tool_kit.sh"

SCRIPT_NAME="install_vtst.sh"
load_package_vars vtst

BUILDDIR="${TOOLCHAIN_BUILDDIR:-${TOOLCHAIN_ROOT}/build}"
INSTALL_ROOT="${TOOLCHAIN_INSTALL_ROOT:-${TOOLCHAIN_ROOT}/install}"
pkg_install_dir="${INSTALL_ROOT}/vtst-${vtst_ver}"
vtst_code_dir="${pkg_install_dir}/${vtst_subdir}"
install_lock_file="${pkg_install_dir}/install_successful"
vtst_pkg="vtstcode-${vtst_commit}.tar.gz"
extract_root="${BUILDDIR}/vtstcode-${vtst_commit}"
setup_file="${BUILDDIR}/setup_vtst"

log() { printf '\033[1;34m[vtst]\033[0m %s\n' "$*"; }
die() { printf '\033[1;31m[vtst]\033[0m %s\n' "$*" >&2; exit 1; }

write_setup_snippet() {
  cat > "${setup_file}" << EOF
# Generated by ${SCRIPT_NAME} — source from an MSYS2 UCRT64 shell
# VTST / vtstcode ${vtst_ver} (commit ${vtst_commit}; Apache-2.0 upstream)
# Respect a user override (e.g. toolchain/local.env) if already set.
if [ -z "\${VTST_CODE_DIR:-}" ]; then
  export VTST_CODE_DIR="${vtst_code_dir}"
fi
EOF
  mkdir -p "${pkg_install_dir}"
  cp -f "${setup_file}" "${INSTALL_ROOT}/setup_vtst"
  cat > "${pkg_install_dir}/setup_vtst.env" << EOF
# Generated by ${SCRIPT_NAME}
if [ -z "\${VTST_CODE_DIR:-}" ]; then
  export VTST_CODE_DIR="${vtst_code_dir}"
fi
EOF
  log "wrote ${setup_file} and ${INSTALL_ROOT}/setup_vtst"
  log "VTST_CODE_DIR tip -> ${vtst_code_dir}"
}

mkdir -p "${BUILDDIR}" "${INSTALL_ROOT}"
cd "${BUILDDIR}"

if [ -f "${install_lock_file}" ] && [ -f "${vtst_code_dir}/chain.F" ]; then
  if [ "${FORCE_REBUILD:-0}" != "1" ]; then
    log "vtst-${vtst_ver} already installed at ${vtst_code_dir}; writing setup and exiting."
    write_setup_snippet
    report_timing "vtst"
    exit 0
  fi
  log "FORCE_REBUILD=1: removing ${pkg_install_dir}"
  rm -rf "${pkg_install_dir}"
fi

echo "==================== Installing VTST / ${vtst_subdir} ===================="
log "commit=${vtst_commit}"
log "pin_sha256=${vtst_sha256}"
log "prefix=${pkg_install_dir}"

retrieve_package "${vtst_sha256}" "${vtst_pkg}" "${vtst_url}" ||
  die "retrieve_package failed (SHA256 pin ${vtst_sha256})"

rm -rf "${extract_root}"
# GitHub archive top dir is vtstcode-<commit>/
extract_verified_archive "${vtst_sha256}" "${vtst_pkg}" ||
  die "extract_verified_archive refused unpack (SHA256 gate)"

src_tree=""
if [ -d "${extract_root}/${vtst_subdir}" ]; then
  src_tree="${extract_root}/${vtst_subdir}"
elif [ -d "${BUILDDIR}/vtstcode-${vtst_commit}/${vtst_subdir}" ]; then
  src_tree="${BUILDDIR}/vtstcode-${vtst_commit}/${vtst_subdir}"
else
  found="$(find "${BUILDDIR}" -maxdepth 3 -type d -name "${vtst_subdir}" 2>/dev/null | head -n1 || true)"
  if [ -n "${found}" ] && [ -f "${found}/chain.F" ]; then
    src_tree="${found}"
  fi
fi
[ -n "${src_tree}" ] && [ -f "${src_tree}/chain.F" ] ||
  die "could not locate ${vtst_subdir}/chain.F after extract under ${BUILDDIR}"

rm -rf "${pkg_install_dir}"
mkdir -p "${pkg_install_dir}"
cp -a "${src_tree}" "${vtst_code_dir}"
[ -f "${vtst_code_dir}/chain.F" ] || die "install failed: missing ${vtst_code_dir}/chain.F"

{
  echo "vtst-${vtst_ver}"
  echo "subdir=${vtst_subdir}"
  echo "commit=${vtst_commit}"
  echo "sha256=${vtst_sha256}"
  date -u '+%Y-%m-%dT%H:%M:%SZ'
} > "${install_lock_file}"

write_setup_snippet
log "installed to ${vtst_code_dir}"
report_timing "vtst"
